version: '3.4'

services:
  live-scores-api:
    image: crawler
    ports: 
      - "8080:80"
    build:
      context: ./LiveScoresAPI
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - "rabbitmq"
  live-scores-crawler:
    image: crawler
    build:
      context: ./LiveScoresCrawlerSource
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - "rabbitmq"
  rabbitmq: # login guest:guest
    image: rabbitmq:3-management
    hostname: "rabbitmq"
    labels:
      NAME: "rabbitmq"
    ports:
    - "4369:4369"
    - "5671:5671"
    - "5672:5672"
    - "25672:25672"
    - "15671:15671"
    - "15672:15672"
