apiVersion: v1
kind: Service
metadata:
  name: live-scores-crawler-service
spec:
  type: LoadBalancer
  ports:
  - port: 5002
    targetPort: 80
  selector:
    web-service: live-scores-crawler

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: live-scores-crawler-service
spec:
  selector:
    matchLabels:
      web-service: live-scores-crawler
  template:
    metadata:
      labels:
        web-service: live-scores-crawler
        system: server
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                web-service: live-scores-crawler
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: live-scores-crawler-service
        image: viktordakov97/livescorescrawlersource:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "512Mi"
            cpu: "250m"
        env:
        - name: MessageQueueSettings__Host
          valueFrom:
            configMapKeyRef:
              name: environment-settings
              key: event-bus-host
        - name: MessageQueueSettings__UserName
          valueFrom:
            configMapKeyRef:
              name: environment-settings
              key: event-bus-user
        - name: MessageQueueSettings__Password
          valueFrom:
            secretKeyRef:
              name: environment-secrets
              key: event-bus-password
