apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: live-scores-api-service-data
spec:
  accessModes:
  - ReadWriteOnce
  - ReadOnlyMany 
  resources:
    requests:
      storage: 10Mi

---

apiVersion: v1
kind: Service
metadata:
  name: live-scores-api-service
spec:
  type: LoadBalancer
  ports:
  - port: 5003
    targetPort: 80
  selector:
    web-service: live-scores-api

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: live-scores-api-service
spec:
  selector:
    matchLabels:
      web-service: live-scores-api
  template:
    metadata:
      labels:
        web-service: live-scores-api
        system: server
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                web-service: live-scores-api
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: live-scores-api-service
        image: viktordakov97/livescoresapi:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "512Mi"
            cpu: "250m"
        env:
        - name: ConnectionStrings__DefaultConnection
          valueFrom:
            secretKeyRef:
              name: environment-secrets
              key: live-scores-api-service-connection-string
        - name: MessageQueueSettings__Host
          valueFrom:
            configMapKeyRef:
              name: environment-settings
              key: event-bus-host
        - name: MessageQueueSettings__UserName
          valueFrom:
            configMapKeyRef:
              name: environment-settings
              key: event-bus-user
        - name: MessageQueueSettings__Password
          valueFrom:
            secretKeyRef:
              name: environment-secrets
              key: event-bus-password
        volumeMounts:
        - name: live-scores-api-service-data
          mountPath: /root/.aspnet/DataProtection-Keys
      volumes:
      - name: live-scores-api-service-data
        persistentVolumeClaim:
          claimName: live-scores-api-service-data
