apiVersion: v1
kind: ConfigMap
metadata:
  name: environment-settings
data:
  event-bus-host: event-bus
  event-bus-user: rabbitmquser
---


apiVersion: v1
kind: Secret
metadata:
 name: environment-secrets
data:
 live-scores-api-database-sa-password: aWRlbnRpdHlEYXRhYmFzZVBhc3N3b3JkMTIhQA==
 live-scores-api-service-connection-string: U2VydmVyPXNxbHNlcnZlcjtEYXRhYmFzZT1HYW1lc0RhdGFiYXNlO1VzZXIgSWQ9c2E7IFBhc3N3b3JkPXlvdXJTdHJvbmdQYXNzd29yZDEyIUA7TXVsdGlwbGVBY3RpdmVSZXN1bHRTZXRzPXRydWU=
 event-bus-password: cmFiYml0bXFQYXNzd29yZDEyIQ== 
